package com.examenweb2021.model.entities;
// Generated 28/06/2021 08:59:35 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reporte generated by hbm2java
 */
@Entity
@Table(name = "reporte", catalog = "conexiones")
public class Reporte implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Connectiontoken connectiontoken;
	private String file;
	private Date datecreate;
	private String state;
	private String description;
	private String name;
	private Set<Seguimiento> seguimientos = new HashSet<Seguimiento>(0);

	public Reporte() {
	}

	public Reporte(Connectiontoken connectiontoken, String file, Date datecreate, String state, String description,
			String name, Set<Seguimiento> seguimientos) {
		this.connectiontoken = connectiontoken;
		this.file = file;
		this.datecreate = datecreate;
		this.state = state;
		this.description = description;
		this.name = name;
		this.seguimientos = seguimientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "conexion")
	public Connectiontoken getConnectiontoken() {
		return this.connectiontoken;
	}

	public void setConnectiontoken(Connectiontoken connectiontoken) {
		this.connectiontoken = connectiontoken;
	}

	@Column(name = "file", length = 100)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreate", length = 19)
	public Date getDatecreate() {
		return this.datecreate;
	}

	public void setDatecreate(Date datecreate) {
		this.datecreate = datecreate;
	}

	@Column(name = "state", length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reporte")
	public Set<Seguimiento> getSeguimientos() {
		return this.seguimientos;
	}

	public void setSeguimientos(Set<Seguimiento> seguimientos) {
		this.seguimientos = seguimientos;
	}

}
