package com.examenweb2021.model.entities;
// Generated 28/06/2021 08:59:35 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seguimiento generated by hbm2java
 */
@Entity
@Table(name = "seguimiento", catalog = "conexiones")
public class Seguimiento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Reporte reporte;
	private Date dategenerate;
	private Short state;
	private String result;
	private String detailrequest;
	private String type;
	private String filegenerate;

	public Seguimiento() {
	}

	public Seguimiento(Reporte reporte, Date dategenerate, Short state, String result, String detailrequest,
			String type, String filegenerate) {
		this.reporte = reporte;
		this.dategenerate = dategenerate;
		this.state = state;
		this.result = result;
		this.detailrequest = detailrequest;
		this.type = type;
		this.filegenerate = filegenerate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "report")
	public Reporte getReporte() {
		return this.reporte;
	}

	public void setReporte(Reporte reporte) {
		this.reporte = reporte;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dategenerate", length = 19)
	public Date getDategenerate() {
		return this.dategenerate;
	}

	public void setDategenerate(Date dategenerate) {
		this.dategenerate = dategenerate;
	}

	@Column(name = "state")
	public Short getState() {
		return this.state;
	}

	public void setState(Short state) {
		this.state = state;
	}

	@Column(name = "result", length = 500)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "detailrequest", length = 1000)
	public String getDetailrequest() {
		return this.detailrequest;
	}

	public void setDetailrequest(String detailrequest) {
		this.detailrequest = detailrequest;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "filegenerate", length = 100)
	public String getFilegenerate() {
		return this.filegenerate;
	}

	public void setFilegenerate(String filegenerate) {
		this.filegenerate = filegenerate;
	}

}
