package com.examenweb2021.model.entities;
// Generated 28/06/2021 08:59:35 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typedb generated by hbm2java
 */
@Entity
@Table(name = "typedb", catalog = "conexiones")
public class Typedb implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String id;
	private String description;
	private String driver;
	private String aditional;
	private Set<Connectiontoken> connectiontokens = new HashSet<Connectiontoken>(0);

	public Typedb() {
	}

	public Typedb(String id) {
		this.id = id;
	}

	public Typedb(String id, String description, String driver, String aditional,
			Set<Connectiontoken> connectiontokens) {
		this.id = id;
		this.description = description;
		this.driver = driver;
		this.aditional = aditional;
		this.connectiontokens = connectiontokens;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "driver", length = 200)
	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	@Column(name = "aditional", length = 500)
	public String getAditional() {
		return this.aditional;
	}

	public void setAditional(String aditional) {
		this.aditional = aditional;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typedb")
	public Set<Connectiontoken> getConnectiontokens() {
		return this.connectiontokens;
	}

	public void setConnectiontokens(Set<Connectiontoken> connectiontokens) {
		this.connectiontokens = connectiontokens;
	}

}
